{
  "hash": "2d710559204109d3b252389ebb4d1200",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Study 1\"\nauthor: \"khoi tran\"\ndate: last-modified\nformat: html\neditor: visual\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(tidyverse)\n\nconf_level <- 0.90   \nalpha <- 1 - conf_level\n\ntheme_set(theme_light()) \nknitr::opts_chunk$set(comment=NA)\n```\n:::\n\n\n# Set Up & Data Import\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nhanesA)\nlibrary(tidyverse)\n#Here, I pull in P_DEMO data from nhanes and save it\ndemo<-nhanes(\"P_DEMO\", translated = FALSE)|>tibble() \nglu<-nhanes(\"P_GLU\", translated = FALSE)|>tibble()\ndiq<-nhanes(\"P_DIQ\", translated = FALSE)|>tibble()\nalq<-nhanes(\"P_ALQ\", translated = FALSE)|>tibble()\n\n#Saving the RDS\nsaveRDS(demo, \"data/P_DEMO.Rds\") \nsaveRDS(glu, \"data/P_GLU.Rds\")\nsaveRDS(diq,\"data/P_DIQ.Rds\")\nsaveRDS(alq, \"data/P_ALQ.Rds\")\n\n\n#reading data as tibble\ndemo<-readRDS(\"data/P_DEMO.Rds\") \nglu<-readRDS(\"data/P_GLU.Rds\")\ndiq<-readRDS(\"data/P_DIQ.Rds\")\nalq<-readRDS(\"data/P_ALQ.Rds\")\n```\n:::\n\n\n# Data Cleaning\n\nFor all analyses, I will take data from the demographic (P_DEMO), diabetes (P_DIQ), glucose levels (P_GLU), and alcohol consumption (P_ALQ) datasets. I first merge all four datasets into a single dataframe called all_raw. Then I filter the raw, merged dataframe to include only participants who have lab and questionnaire results and are adults between the ages of 21 and 79. This filtered, merged dataframe is named all_clean, with a total of 7,853 unique observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(naniar)\nall_raw <- demo |>\n  left_join(diq, by = \"SEQN\") |>\n  left_join(glu, by = \"SEQN\") |>\n  left_join(alq, by = \"SEQN\")\n\nall_clean <- all_raw |>\n  filter(RIDSTATR == 2, RIDAGEYR >= 21, RIDAGEYR <= 79)\nn_distinct(all_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7853\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(all_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7853\n```\n\n\n:::\n:::\n\n\n## Analysis A\n\nIn this analysis, I want to look at the difference between reported and recommended LDL amongst diabetic subjects who take diabetic pills. Here, I use the dataset DIQ070 containing diabetic subjects and select subjects encoded by 1 (DIQ070==1), indicating they're diabetic and currently taking diabetic pills. Then, I remove the reported and recommended LDL values from subjects who refused to answer, don't know, or have missing values for whether they take diabetic pills using the mutate function. This gives me the diqA dataframe that includes the reported and recommended LDL values from diabetic subjects who take diabetic pills.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiqA <- all_clean |>\n  filter(DIQ070 == 1) |>                \n  mutate(\n    reported_ldl = DID320 |> na_if(5555) |> na_if(6666) |> na_if(7777) |> na_if(9999),\n    goal_ldl     = DID330 |> na_if(6666) |> na_if(7777) |> na_if(9999)\n  ) |>\n  filter(!is.na(reported_ldl), !is.na(goal_ldl))\n\nn_distinct(diqA$reported_ldl)   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 61\n```\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(diqA$goal_ldl)       \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 26\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(diqA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 76\n```\n\n\n:::\n:::\n\n\n## Analysis B\n\nIn this analysis, I want to compare the fasting glucose levels of non-diabetic subjects in males vs. females. To do this, I filtered out non-diabetic subjects from the DIQ010 dataset and selected only subjects with available fasting glucose levels from the LBXGLU dataset. Then, I divided this cohort into subgroups by sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiqB <- all_clean |>\n  filter(\n    DIQ010 == 2,                 \n    RIAGENDR %in% c(1, 2),      \n    !is.na(LBXGLU)              \n  ) |>\n  mutate(\n    sex = case_when(\n      RIAGENDR == 1 ~ \"Male\",\n      RIAGENDR == 2 ~ \"Female\"\n    )\n  )\ndiqB |> count(sex)        \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  sex        n\n  <chr>  <int>\n1 Female  1588\n2 Male    1409\n```\n\n\n:::\n\n```{.r .cell-code}\nn_distinct(diqB$LBXGLU) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 122\n```\n\n\n:::\n:::\n\n\n## Analysis C\n\nIn this analysis, I want to compare baseline fasting glucose levels between groups with varying alcohol consumption levels. The ALQ142 dataset classifies subjects into different groups based on how many days they have had 4 or 5 drinks in the past 12 months. I merged these groups together to create 4 broader sub-groups that signify the subjects' drinking habits. The groups include: social drinker, intermediate, and heavy drinker, with social drinker having the fewest days with 4 or 5 drinks and heavy drinker having the most. For the \"non-drinker\" control group, I used subjects that responded \"Never\" in the ALQ121 dataset, which asks how often they drank alcoholic beverages in the past 12 months.\n\nBelow is the code where I filtered for only non-diabetic subjects and set the criteria for my four subgroups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiqC <- all_clean |>\n  filter(DIQ010==2)|>\n  mutate(\n    alcohol_group = case_when(\n      ALQ121 == 0        ~ \"Nondrinker\",\n      ALQ142 %in% 7:10    ~ \"Social drinker\",\n      ALQ142 %in% 4:6     ~ \"Intermediate\",\n      ALQ142 %in% 1:3     ~ \"Heavy drinker\",\n      TRUE                ~ NA_character_\n    ),\n    alcohol_group = factor(alcohol_group,\n                            levels = c(\"Nondrinker\", \"Social drinker\", \"Intermediate\",\n                                       \"Heavy drinker\"))) |>\n  filter(!is.na(alcohol_group))\nglu_C <- diqC |> filter(!is.na(LBXGLU))\nglu_C |> count(alcohol_group)  \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  alcohol_group      n\n  <fct>          <int>\n1 Nondrinker       480\n2 Social drinker   606\n3 Intermediate     278\n4 Heavy drinker     95\n```\n\n\n:::\n:::\n\n\n## Analysis D\n\nIn this analysis, my two categorical variables are sex (male or female) and retinopathy status (with or without) in diabetic subjects. To create the cohort groups, I first filter for only diabetic subjects from those who responded \"Yes\" in the DIQ010 dataset. For the sex variable, I use the mutate function to create the male and female subgroups based on their encoded response in the RIAGENDR dataset. The same method is used on the DIQ080 dataset to create the with- and without-retinopathy subgroups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetics <- all_clean |>\n  filter(DIQ010 == 1) |>                       \n  filter(DIQ080 %in% c(1, 2)) |>\n  mutate(\n    sex = factor(RIAGENDR, levels = c(1, 2), labels = c(\"Male\", \"Female\")),\n    retinopathy = factor(DIQ080, levels = c(1, 2), labels = c(\"Yes\", \"No\"))\n  )\ntab_sex <- table(diabetics$retinopathy, diabetics$sex)\ntab_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      Male Female\n  Yes  115    114\n  No   517    429\n```\n\n\n:::\n:::\n\n\n# Codebook\n\n| Variable | Description |\n|-----------------------------------:|:-----------------------------------|\n| `diabetics` | subjects with reported diabetes |\n| `sex` | female or male |\n| `nondrinker` | have not had alcohol in the past 12 months |\n| `occasional_drinker` | have had 4 or 5 drinks/day once a month to 1-2 times in the past 12 months |\n| `social_drinker` | have had 4 or 5 drinks/day 2 times a week to 2-3 times a month in the past 12 months |\n| `heavy_drinker` | have had 4 or 5 drinks/day every day to 3-4 times a week in the past 12 months |\n| `retinopathy` | Retinopathy status of diabetic subjects. Yes = have retinopathy; No = does not have retinopathy |\n| `reported_ldl` | LDL level reported by subjects (mg/dL) |\n| `goal_ldl` | LDL level recommended by doctor (mg/dL) |\n\n# Analysis A: Comparing 2 Means with Paired Samples\n\n*Among diabetics who take diabetic pills, is there a difference between their reported LDL cholesterol and the LDL goal their doctor recommended?*\n\n## Research question\n\nDiabetes patients are prescribed diabetic pills to control their blood sugar levels. This can potentially modulate other clinically relevant measurements such as total serum LDL, which is heightened in diabetes. Hence, it is interesting to examine whether, among diabetics who take diabetic pills, **there is a difference between their reported LDL levels and the ideal LDL goal recommended by their doctor.**\n\n## About the data\n\nThe comparison is being made between reported and recommended LDL levels (in mg/dL). As shown earlier, the data have been cleaned to include only diabetic subjects who are taking diabetic pills and have reported their most recent LDL levels. As it has been shown that LDL levels tend to rise with age, it is important that the relative age between all subjects for this analysis is evenly matched and is not skewed towards either direction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nageA<-mosaic::favstats(~ RIDAGEYR, data = diqA) |>\n  mutate(IQR = Q3 - Q1, .after = Q3)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n```\n\n\n:::\n\n```{.r .cell-code}\nknitr::kable(ageA)\n```\n\n::: {.cell-output-display}\n\n\n|   | min|    Q1| median|    Q3|  IQR| max|     mean|       sd|  n| missing|\n|:--|---:|-----:|------:|-----:|----:|---:|--------:|--------:|--:|-------:|\n|   |  36| 58.75|   65.5| 71.25| 12.5|  79| 64.06579| 10.14999| 76|       0|\n\n\n:::\n\n```{.r .cell-code}\nmed_age <- median(diqA$RIDAGEYR)\nageA<-ggplot(diqA, aes(x = RIDAGEYR)) +\n  geom_histogram(binwidth = 5, fill = \"darkgreen\", color = \"black\", alpha = 0.8) +\n  geom_vline(xintercept = med_age, color = \"red\",linetype = \"dashed\", linewidth = 0.9) +\n  annotate(\"text\", x = med_age, y = Inf,label = paste0(\"Median = \", med_age),color = \"red\", hjust = 1.1, vjust = 2.3, size = 4.5) +\n  labs(x = \"Age (years)\", y = \"Count\",title = \"Age distribution of Subjects\") +\n  theme_minimal() +\n  theme(\n    plot.title   = element_text(size = 10, face = \"bold\"),\n    axis.title   = element_text(size = 8),\n    axis.text    = element_text(size = 8)\n  )\nageA\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisA_data-1.png){width=672}\n:::\n:::\n\n\nFrom the summary and histogram showing the age distribution of the subjects in this analysis, it is clear that the histogram is slightly left skewed with the median age of 65.5 years. This is important to keep in mind for interpreting the results as age is a known factor influencing LDL levels.\n\nTo assess normality of the reported LDL distribution, I have made the following plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqA<-ggplot(diqA, aes(x = reported_ldl)) +\n  geom_histogram(aes(y = after_stat(density)),bins = 10, fill = \"darkgreen\",color = \"black\") +\n  stat_function(fun = dnorm, args = list(\n      mean = mean(diqA$reported_ldl),\n      sd = sd(diqA$reported_ldl)),\n    color = \"red\",\n    linewidth = 1) +\n  labs(\n    title = \"Histogram of Reported LDL Values\",\n    x = \"Reported LDL\",\n    y = \"Density\")\nqqA<-ggplot(diqA, aes(sample = reported_ldl)) +\n  stat_qq() +\n  stat_qq_line() +\n  labs(\n    title = \"Q-Q Plot of Reported LDL Values\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\")\nbA<-ggplot(diqA, aes(x = \"\", y = reported_ldl)) +\n  geom_boxplot(fill = \"darkgreen\", alpha = 0.7, width = 0.4, outlier.alpha = 0.5) +\n  labs(x = NULL, y = \"Reported LDL (mg/dL)\",\n       title = \"Boxplot of Reported LDL\")\ncombinedA<-qA+(qqA/bA)&\n  theme(plot.title  = element_text(size = 10, face=\"bold\"),\n        axis.title = element_text(size=8),\n        plot.margin = margin(10, 20, 10, 20))  \ncombinedA\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisA_data2-1.png){width=672}\n:::\n:::\n\n\nThe S-shaped curve from the q-q plot suggests a uniform distribution. However, based on the histogram and boxplot, the distribution of reported LDL values resembles a right-skewed distribution. The curve at the right end of the tail is likely due to extreme outliers illustrated by the histogram and boxplot. From these plots, we cannot assume normality of the reported LDL values.\n\n## Analysis\n\nAs shown in the data exploration part, the distribution of reported LDL values is right-skewed. Due to this, comparing the medians of the two paired samples (reported vs. recommended LDL) will be more appropriate, as the median is more resistant to outliers than the mean.\n\nIn addition, even though we cannot assume normality, the sample sizes for both populations are larger than 30. The paired t-test cannot compare medians, so the bootstrap method is more appropriate. I created the variable diqA_diff to generate the difference between the reported and recommended LDL values, then used the bootstrap method to compare the median difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiqA_diff <- diqA |> mutate(diff = reported_ldl - goal_ldl)\nset.seed(431)\nboot_med <- replicate(10000, median(sample(diqA_diff$diff, replace = TRUE)))\ntibble(\n  `Observed median difference` = median(diqA_diff$diff),\n  `Lower 90% CI`               = quantile(boot_med, 0.05),\n  `Upper 90% CI`               = quantile(boot_med, 0.95)) |>\n  knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n| Observed median difference| Lower 90% CI| Upper 90% CI|\n|--------------------------:|------------:|------------:|\n|                        2.5|            0|           10|\n\n\n:::\n\n```{.r .cell-code}\nbA<-diqA |>\n  pivot_longer(c(reported_ldl, goal_ldl), names_to = \"type\", values_to = \"ldl\") |>\n  mutate(type = recode(type, reported_ldl = \"Reported LDL\", goal_ldl = \"Recommended LDL\")) |>\n  ggplot(aes(x = type, y = ldl, fill = type)) +\n  geom_boxplot(alpha = 0.7, outlier.alpha = 0.4) +\n  scale_fill_manual(values = c(\"Reported LDL\" = \"steelblue\", \"Recommended LDL\" = \"darkgreen\")) +\n  labs(x = NULL, y = \"LDL levels (mg/dL)\")\nbA\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisA_test-1.png){width=672}\n:::\n:::\n\n\n## Conclusion\n\nFrom the resulting table, the interval includes 0. Therefore, at 90% confidence level, there is no difference in the median between reported and recommended LDL. In the context of the central question, this means that the diabetic pill does have a positive effect in helping diabetic patients manage LDL levels, which is one of the main clinical outcomes in diabetes.\n\n# Analysis B: Comparing 2 Means with Independent Samples\n\n*Do men have higher baseline fasting plasma glucose levels than women?*\n\n## Research question\n\nIt has been shown that diabetes is more prevalent in the male than female population in the US. Fasting plasma glucose levels are one of the prominent clinical measurements to infer an individual's risk of having diabetes. Hence, it is interesting to examine whether there is an intrinsic sex difference in fasting plasma glucose levels. In this analysis, I want to examine **whether men have higher baseline fasting plasma glucose levels than women?**\n\n## About the data\n\nIn this analysis, I'm comparing fasting plasma glucose levels between non-diabetic men and women. As age has not been shown to influence fasting glucose levels, the age distribution between the subjects of this analysis is not a concern.\n\nTo assess normality of the distributions, I made the following plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_stats <- diqB |>\n  group_by(sex) |>\n  summarise(mean_glu = mean(LBXGLU, na.rm = TRUE),\n            sd_glu   = sd(LBXGLU, na.rm = TRUE),\n            .groups = \"drop\")\nglu_range <- range(diqB$LBXGLU, na.rm = TRUE)\nnorm_curves <- group_stats |>\n  rowwise() |>\n  reframe(\n    sex = sex,\n    glucose = seq(glu_range[1], glu_range[2], length.out = 200),\n    density = dnorm(glucose, mean = mean_glu, sd = sd_glu))\nqB <- ggplot(diqB, aes(x = LBXGLU)) +\n  geom_histogram(aes(y = after_stat(density)), binwidth = 3,\n                 fill = \"darkgreen\", color = NA) +         \n  geom_line(data = norm_curves, aes(x = glucose, y = density),\n            color = \"red\", linewidth = 1) +\n  facet_wrap(~ sex, ncol = 1) +\n  labs(x = \"Fasting plasma glucose (mg/dL)\", y = \"Density\",\n       title = \"Fasting Glucose Distribution by Sex\") +\n  coord_cartesian(xlim = c(46, 422))\n\nqqB <- ggplot(diqB, aes(sample = LBXGLU)) +\n  stat_qq(size=0.6, alpha=0.7) + stat_qq_line(color = \"red\") +\n  facet_wrap(~ sex, ncol = 1) +\n  labs(x = \"Theoretical quantiles\",\n       y = \"Sample quantiles\\n(fasting glucose, mg/dL)\",   \n       title = \"Q-Q Plot of Fasting Glucose by Sex\")\nbB<-ggplot(diqB, aes(x = sex, y = LBXGLU, fill = sex)) +\n  geom_boxplot(alpha = 0.7, outlier.alpha = 0.4) +\n  scale_fill_manual(values = c(\"Male\" = \"steelblue\", \"Female\" = \"red\")) +\n  scale_x_discrete(limits = c(\"Male\", \"Female\")) +\n  labs(x = NULL, y = \"Fasting plasma glucose (mg/dL)\",\n       title = \"Fasting Glucose by Sex\")+\n  coord_flip()\ncombinedB<-bB/(qqB+qB)\ncombinedB &\n  theme(\n    plot.title = element_text(size=8, face=\"bold\"),\n    axis.title=element_text(size=8),\n    plot.margin = margin(10, 20, 10, 20))\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisB_norm-1.png){width=672}\n:::\n:::\n\n\nAs clearly shown by the boxplot and q-q plot, both distributions are strongly right-skewed. This can be due to undiagnosed diabetics who are not reported in the questionnaire. Due to this, we cannot assume normality for either distribution.\n\n## Analysis\n\nAs shown in the data exploration part, we cannot assume normality. However, since the sample sizes for both populations are larger than 30, we can still perform the t-test to compare the means of the two independent samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiqB_test <- t.test(LBXGLU ~ sex, data = diqB, conf.level = conf_level)\ndiqB_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  LBXGLU by sex\nt = -3.7466, df = 2894.9, p-value = 0.0001827\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n90 percent confidence interval:\n -3.902396 -1.520746\nsample estimates:\nmean in group Female   mean in group Male \n            102.3665             105.0781 \n```\n\n\n:::\n\n```{.r .cell-code}\nanaB<-tidy(diqB_test) |>\n  transmute(\n    `Mean, Female`        = estimate1,\n    `Mean, Male`          = estimate2,\n    `Lower 90% CI`        = conf.low,\n    `Upper 90% CI`        = conf.high,\n    `p-value`             = p.value)\n\nkable(anaB, digits = c(2, 2, 2, 2,4), align = \"c\")\n```\n\n::: {.cell-output-display}\n\n\n| Mean, Female | Mean, Male | Lower 90% CI | Upper 90% CI | p-value |\n|:------------:|:----------:|:------------:|:------------:|:-------:|\n|    102.37    |   105.08   |     -3.9     |    -1.52     |  2e-04  |\n\n\n:::\n\n```{.r .cell-code}\nggplot(diqB, aes(x = sex, y = LBXGLU, fill = sex)) +\n  geom_violin()+\n  geom_boxplot(alpha = 0.6, show.legend = FALSE)+\n  coord_flip()+\n  labs(x = NULL, y = \"Fasting plasma glucose (mg/dL)\",\n       title = \"Fasting Plasma Glucose in Non-Diabetic Subjects by Sex\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisB-test-1.png){width=672}\n:::\n:::\n\n\n## Conclusions\n\nThe results indicate that men do have a higher mean baseline fasting glucose level compared to women (105.1 vs 102.4 mg/dL). The resulting interval from the t-test does not include 0. Therefore, at 90% confidence level, there is a statistically significant difference in the mean baseline fasting glucose level between non-diabetic men and women. This is interesting because it suggests that the difference in baseline fasting glucose levels might act as an intrinsic factor contributing to diabetes being more prevalent in the male population compared to the female population.\n\nHowever, this analysis only loosely supports this hypothesis, as the glucose levels on the higher end of the distribution might be due to undiagnosed diabetes in both groups. A controlled experiment using age-matched subjects with similar fasting glucose levels is needed to further strengthen this correlation.\n\n# Analysis C: Comparing X Means with Independent Samples\n\n*Does frequent alcohol consumption affect baseline plasma fasting glucose level?*\n\n## Research question\n\nIt has been shown that alcohol consumption is a prominent risk factor for diabetes. Hence, in this analysis, I want to examine **whether alcohol consumption frequency affects baseline plasma fasting glucose level?**\n\n## About the data\n\nIn this analysis, I want to compare plasma fasting glucose levels among subjects grouped by how often they have 4/5 drinks per day in the past 12 months. As shown in the earlier sections, there are four groups, with non-drinkers serving as the control group for comparisons, and occasional, social, and heavy drinkers. The dataset has been cleaned to include only non-diabetic subjects so that fasting plasma glucose levels are not influenced by diabetes, which is known to directly enhance baseline plasma glucose levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglu_summary<-mosaic::favstats(LBXGLU ~ alcohol_group, data = glu_C)|>\n  mutate(IQR = Q3 - Q1, .after = Q3)\nknitr::kable(glu_summary, digits = 1,\n             caption = \"Fasting plasma glucose (mg/dL) by alcohol group, non-diabetic adults\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Fasting plasma glucose (mg/dL) by alcohol group, non-diabetic adults\n\n|alcohol_group  | min|   Q1| median|    Q3| IQR| max|  mean|   sd|   n| missing|\n|:--------------|---:|----:|------:|-----:|---:|---:|-----:|----:|---:|-------:|\n|Nondrinker     |  47| 95.0|    102| 110.0|  15| 321| 105.8| 21.5| 480|       0|\n|Social drinker |  74| 94.0|    100| 108.0|  14| 408| 103.0| 20.9| 606|       0|\n|Intermediate   |  63| 95.0|    100| 109.0|  14| 303| 102.9| 17.4| 278|       0|\n|Heavy drinker  |  75| 93.5|     99| 105.5|  12| 138|  99.8| 10.8|  95|       0|\n\n\n:::\n:::\n\n\nFrom the summary, we can see that the centers of the groups are relatively similar, with both their means and medians sitting around 100mg/dL. However, the nondrinker, social drinker, and intermediate groups all have maximum values that notably exceed those of the heavy drinker group. The IQR values are similar across all groups, indicating a similar spread. Therefore, the differences in distributions will come mostly from the tails and outliers.\n\nTo assess normality of the distributions of fasting plasma glucose levels of the four groups, I have generated the following plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqC<-ggplot(glu_C, aes(sample = LBXGLU)) +\n  stat_qq(size=0.6, alpha=0.7) +\n  stat_qq_line() +\n  facet_wrap(~ alcohol_group) +\n  labs(\n    title = \"Q-Q Plots of Fasting Plasma Glucose\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\") \ndC<-ggplot(glu_C, aes(x = alcohol_group, y = LBXGLU, fill = alcohol_group)) +\n  geom_boxplot(alpha = 0.6, show.legend = FALSE) +\n  labs(x = NULL, y = \"Fasting plasma glucose (mg/dL)\",\n       title = \"Analysis C: Fasting glucose by alcohol-consumption group\") +\n  theme_minimal()+coord_flip()\ncolours <- c(\"Nondrinker\" = \"grey\", \"Social drinker\" = \"steelblue\", \"Intermediate\" = \"orange\", \"Heavy drinker\" = \"red\")\n\ngroup_stats_C <- glu_C |>\n  group_by(alcohol_group) |>\n  summarise(mean_glu = mean(LBXGLU, na.rm = TRUE),\n            sd_glu   = sd(LBXGLU, na.rm = TRUE),\n            .groups = \"drop\")\nglu_range_C <- range(glu_C$LBXGLU, na.rm = TRUE)\nnorm_curves_C <- group_stats_C |>\n  rowwise() |>\n  reframe(\n    alcohol_group = alcohol_group,\n    glucose = seq(glu_range_C[1], glu_range_C[2], length.out = 200),\n    density = dnorm(glucose, mean = mean_glu, sd = sd_glu))\nhC <- ggplot(glu_C, aes(x = LBXGLU)) +\n  geom_histogram(aes(y = after_stat(density), fill = alcohol_group),binwidth = 3, color = NA) +\n  geom_line(data = norm_curves_C, aes(x = glucose, y = density),color = \"black\", linewidth = 0.7) +\n  scale_fill_manual(values = colours) +\n  coord_cartesian(xlim = c(20, 180))+\n  facet_wrap(~ alcohol_group) +\n  labs(\n    title = \"Fasting Plasma Glucose Histograms\",\n    x = \"Fasting Plasma Glucose (mg/dL)\", y = \"Density\"\n  )\ncombinedC <- dC / (qqC + hC) +\n  plot_layout(heights = c(1, 2)) &\n  theme_minimal() &\n  theme(\n    legend.position = \"none\",\n    plot.title  = element_text(size = 8, face = \"bold\"),\n    axis.title  = element_text(size = 8),\n    plot.margin = margin(10, 20, 10, 20))\ncombinedC\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisC_data-1.png){width=672}\n:::\n:::\n\n\nBased on the violin-boxplot, the nondrinker, social drinker, and intermediate drinker groups are strongly right-skewed, with the exception of the heavy drinker group. This is corroborated by the q-q plot of the three right-skewed groups, which shows a sharp upward curve at the right end. Due to this, we can only assume normality for the heavy drinker group and not the other.\n\n## Analysis\n\nAnalysis of variance (ANOVA) requires normality within each group. This assumption is not satisfied, as 3 out of 4 groups for comparison are right-skewed. However, the size of each group is large enough (shown in the table below) so that this non-normality is tolerable. Therefore, an ANOVA with pre-planned Tukey HSD pairwise comparisons can be done.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglu_C |> count(alcohol_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  alcohol_group      n\n  <fct>          <int>\n1 Nondrinker       480\n2 Social drinker   606\n3 Intermediate     278\n4 Heavy drinker     95\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_glu <- aov(LBXGLU ~ alcohol_group, data = glu_C)\nsummary(aov_glu)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df Sum Sq Mean Sq F value Pr(>F)  \nalcohol_group    3   4082  1360.7   3.413 0.0169 *\nResiduals     1455 580047   398.7                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ntukey<-TukeyHSD(aov_glu, conf.level = conf_level)\n\nanova_tbl <- tidy(aov_glu) |>\n  mutate(term = if_else(term == \"alcohol_group\", \"Alcohol group\", term))\nkable(anova_tbl, digits = c(0, 0, 1, 1, 3, 4), align = \"lccccc\",\n      caption = \"One-way ANOVA: fasting plasma glucose by alcohol-consumption group\")\n```\n\n::: {.cell-output-display}\n\n\nTable: One-way ANOVA: fasting plasma glucose by alcohol-consumption group\n\n|term          |  df  |  sumsq   | meansq | statistic | p.value |\n|:-------------|:----:|:--------:|:------:|:---------:|:-------:|\n|Alcohol group |  3   |  4082.2  | 1360.7 |   3.413   | 0.0169  |\n|Residuals     | 1455 | 580047.2 | 398.7  |    NA     |   NA    |\n\n\n:::\n\n```{.r .cell-code}\ntukey_tbl <- tidy(tukey) |>\n  transmute(\n    Comparison    = contrast,\n    `Mean diff.`  = estimate,\n    `Lower 90% CI`= conf.low,\n    `Upper 90% CI`= conf.high,\n    `Adj. p`      = adj.p.value  )\nkable(tukey_tbl, digits = 2, align = \"lccc\",\n      caption = \"Tukey HSD pairwise comparisons, fasting plasma glucose by alcohol group (90% CI)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Tukey HSD pairwise comparisons, fasting plasma glucose by alcohol group (90% CI)\n\n|Comparison                   | Mean diff. | Lower 90% CI | Upper 90% CI |Adj. p |\n|:----------------------------|:----------:|:------------:|:------------:|:------|\n|Social drinker-Nondrinker    |   -2.82    |    -5.62     |    -0.03     |0.10   |\n|Intermediate-Nondrinker      |   -2.92    |    -6.37     |     0.53     |0.21   |\n|Heavy drinker-Nondrinker     |   -6.02    |    -11.17    |    -0.88     |0.04   |\n|Intermediate-Social drinker  |   -0.09    |    -3.41     |     3.22     |1.00   |\n|Heavy drinker-Social drinker |   -3.20    |    -8.25     |     1.85     |0.47   |\n|Heavy drinker-Intermediate   |   -3.11    |    -8.55     |     2.34     |0.56   |\n\n\n:::\n\n```{.r .cell-code}\nggplot(glu_C, aes(x = alcohol_group,y=LBXGLU,fill = alcohol_group)) +\n  geom_violin(alpha=0.7, trim=TRUE)+\n  scale_fill_manual(values=colours)+\n  geom_boxplot(width=0.2, fill=\"black\", outlier.alpha=0.4)+\n  labs(\n    title = \"Fasting Plasma Glucose Distribution\",x = NULL,y = \"Fasting Plasma Glucose (mg/dL)\")+\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisC-test-1.png){width=672}\n:::\n:::\n\n\n## Conclusion\n\nThe ANOVA results indicate there is a statistically significant difference in fasting glucose across alcohol consumption groups, with a p-value of 0.017. The pairwise Tukey HSD comparison shows that the only significant difference comes from the comparison between heavy drinkers and non-drinkers, with the resulting interval not including 0 and a p-value smaller than 0.05. In the context of my research question, this result shows that alcohol consumption does affect fasting glucose levels, but only at high-frequency consumption.\n\nInterestingly, the direction of the difference is unexpected, as nondrinkers are shown to have higher fasting glucose levels than heavy drinkers. This is the opposite of what I predicted, as overt alcohol consumption is known to be a risk factor for diabetes; hence, I expected increased alcohol consumption would increase fasting glucose levels. This unexpected result can be accounted for by the fact that the non-drinker group contains a lot more outliers towards the higher end of the fasting glucose level distribution, compared to the heavy drinker group. This can also be due to other confounding factors, such as other underlying health issues or unreported diabetes, etc., that are not controlled for in the dataset.\n\n# Analysis D: Analyzing a 2x2 Table\n\n*Is there a sex difference in the development of diabetes in diabetic male vs female population*\n\n## Research question\n\nIt has been shown that diabetes is more prevalent in males than females in the US. However, it is unclear whether sex can pose as an intrinsic factor influencing disease progression or severity. The occurrence of diabetic retinopathy is used clinically to gauge overall disease severity and assess end-organ damage. Using retinopathy occurrence as a marker for severe diabetes, I want to investigate whether there is a sex difference in the development of diabetes in diabetic male vs. female populations by asking: \\*\\* Is severe diabetes more common in males than in females?\\*\\*\n\n## About the data\n\nAs mentioned in the previous section, I use the occurrence of retinopathy as an indicator of severe diabetes for this analysis. Age is a prominent factor influencing retinopathy occurrence, as it has been shown clinically to increase with aging. Hence, I want to ensure that the subject cohort used in this analysis, which is grouped by sex and retinopathy status, has similar age distributions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_sum<-mosaic::favstats(RIDAGEYR ~ sex, data = diabetics)|>\n  mutate(IQR = Q3 - Q1, .after = Q3)\nknitr::kable(age_sum)\n```\n\n::: {.cell-output-display}\n\n\n|sex    | min| Q1| median| Q3| IQR| max|     mean|       sd|   n| missing|\n|:------|---:|--:|------:|--:|---:|---:|--------:|--------:|---:|-------:|\n|Male   |  22| 55|     63| 70|  15|  79| 61.71044| 10.73215| 632|       0|\n|Female |  22| 52|     61| 68|  16|  79| 59.26888| 11.90636| 543|       0|\n\n\n:::\n\n```{.r .cell-code}\naD<-ggplot(diabetics, aes(x=sex, y=RIDAGEYR, fill=sex))+\n  geom_boxplot()+\n  labs(\n    title = \"Age Distribution of Male and Female Subjects\", x = \"Sex\", y = \"Age (years)\")+\n    scale_fill_manual(values = c(\"Male\" = \"steelblue\", \"Female\" = \"red\")) \nretino_sum<-mosaic::favstats(RIDAGEYR ~ retinopathy, data = diabetics)|>\n    mutate(IQR = Q3 - Q1, .after = Q3)\nknitr::kable(retino_sum)\n```\n\n::: {.cell-output-display}\n\n\n|retinopathy | min| Q1| median| Q3| IQR| max|     mean|       sd|   n| missing|\n|:-----------|---:|--:|------:|--:|---:|---:|--------:|--------:|---:|-------:|\n|Yes         |  30| 55|     63| 69|  14|  79| 61.72926| 10.62957| 229|       0|\n|No          |  22| 53|     62| 69|  16|  79| 60.30444| 11.50653| 946|       0|\n\n\n:::\n\n```{.r .cell-code}\nrD<-ggplot(diabetics, aes(x=retinopathy, y=RIDAGEYR, fill=retinopathy))+\n  geom_boxplot()+\n  labs(title = \"Age Distribution of Based on Retinopathy Status\",x = \"Retinopathy Status\",y = \"Age (years)\")+\n    scale_fill_manual(values = c(\"Yes\" = \"steelblue\", \"No\" = \"grey\"))\ncombinedD <- (aD | rD) &\n  theme(plot.title  = element_text(size = 10, face=\"bold\"),\n        plot.margin = margin(10, 20, 10, 20))   \ncombinedD\n```\n\n::: {.cell-output-display}\n![](study-1_files/figure-html/analysisD_data-1.png){width=672}\n:::\n:::\n\n\nAs shown in the summaries and boxplots, the age distribution between males and females, as well as retinopathy status, is relatively similar. All sub-groups have similar center and spread, with the mean and median age around 60 years old, and an IQR of 15-16. This similar age distribution across all sub-groups controls for age as a contributing factor to retinopathy status, which strengthens the outcome of this analysis on the effect of sex on diabetes severity.\n\n## Analysis\n\nFor this analysis, I will be doing relative risk, odds ratio, and risk difference comparisons. These comparisons require the values to be independent, with each value in a group representing one person counted exactly once. The data cleaning done previously satisfies this condition. These comparisons rely on normality, which is not an issue due to the large sample size of each group.\n\nBelow is the work for these analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(kableExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'kableExtra'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n\n```{.r .cell-code}\ntab_pct <- tab_sex |>\n  addmargins() |>\n  as.data.frame.matrix()\ncol_totals <- tab_pct[\"Sum\", ]\ntab_display <- tab_pct\nfor (col in c(\"Male\", \"Female\")) {tab_display[[col]] <- paste0(tab_pct[[col]], \" (\",\n                                round(100 * tab_pct[[col]] / col_totals[[col]], 1), \"%)\")}\ntab_display$Sum <- paste0(tab_pct$Sum, \" (\",\n                           round(100 * tab_pct$Sum / col_totals$Sum, 1), \"%)\")\ntab_display <- tab_display |>\n  tibble::rownames_to_column(\"Retinopathy\")\nkable(tab_display, align = \"lccc\",\n      caption = \"Retinopathy by sex among diabetics, count (column %)\") |>\n  kable_styling(full_width = FALSE) |>\n  row_spec(nrow(tab_display), bold = TRUE) |>\n  column_spec(4, bold = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Retinopathy by sex among diabetics, count (column %)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Retinopathy </th>\n   <th style=\"text-align:center;\"> Male </th>\n   <th style=\"text-align:center;\"> Female </th>\n   <th style=\"text-align:center;\"> Sum </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Yes </td>\n   <td style=\"text-align:center;\"> 115 (18.2%) </td>\n   <td style=\"text-align:center;\"> 114 (21%) </td>\n   <td style=\"text-align:center;font-weight: bold;\"> 229 (19.5%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> No </td>\n   <td style=\"text-align:center;\"> 517 (81.8%) </td>\n   <td style=\"text-align:center;\"> 429 (79%) </td>\n   <td style=\"text-align:center;font-weight: bold;\"> 946 (80.5%) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;font-weight: bold;\"> Sum </td>\n   <td style=\"text-align:center;font-weight: bold;\"> 632 (100%) </td>\n   <td style=\"text-align:center;font-weight: bold;\"> 543 (100%) </td>\n   <td style=\"text-align:center;font-weight: bold;font-weight: bold;\"> 1175 (100%) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_sex <- table(diabetics$retinopathy, diabetics$sex)\ntab_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      Male Female\n  Yes  115    114\n  No   517    429\n```\n\n\n:::\n\n```{.r .cell-code}\ntwoby2 <- function(tab) {\n  a <- tab[\"Yes\", \"Male\"];   b <- tab[\"No\", \"Male\"]\n  c <- tab[\"Yes\", \"Female\"]; d <- tab[\"No\", \"Female\"]\n  risk_m <- a / (a + b); risk_f <- c / (c + d)\n  rr <- risk_m / risk_f; or_ <- (a * d) / (b * c); rd <- risk_m - risk_f\n  z <- qnorm(1 - alpha / 2)\n  se_logrr <- sqrt(1/a - 1/(a+b) + 1/c - 1/(c+d))\n  se_logor  <- sqrt(1/a + 1/b + 1/c + 1/d)\n  se_rd     <- sqrt(risk_m*(1-risk_m)/(a+b) + risk_f*(1-risk_f)/(c+d))\n  list(\n    risk_male = risk_m, risk_female = risk_f,\n    RR = rr, RR_CI = exp(log(rr) + c(-1, 1) * z * se_logrr),\n    OR = or_, OR_CI = exp(log(or_) + c(-1, 1) * z * se_logor),\n    RD = rd, RD_CI = rd + c(-1, 1) * z * se_rd\n  )\n}\n\nres <- twoby2(tab_sex)\n\nsummary_tbl <- tibble(\n  Measure    = c(\"Relative Risk (Male/Female)\", \"Odds Ratio (Male/Female)\",\n                 \"Risk Difference (Male-Female)\"),\n  Estimate   = c(res$RR, res$OR, res$RD),\n  `Lower 90% CI` = c(res$RR_CI[1], res$OR_CI[1], res$RD_CI[1]),\n  `Upper 90% CI` = c(res$RR_CI[2], res$OR_CI[2], res$RD_CI[2])\n)\n\nkable(summary_tbl, digits = 3,\n      caption = \"Retinopathy in male vs. female diabetics: RR, OR, and risk difference (90% CI)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Retinopathy in male vs. female diabetics: RR, OR, and risk difference (90% CI)\n\n|Measure                       | Estimate| Lower 90% CI| Upper 90% CI|\n|:-----------------------------|--------:|------------:|------------:|\n|Relative Risk (Male/Female)   |    0.867|        0.713|        1.053|\n|Odds Ratio (Male/Female)      |    0.837|        0.657|        1.067|\n|Risk Difference (Male-Female) |   -0.028|       -0.066|        0.010|\n\n\n:::\n:::\n\n\n## Conclusion\n\nThe 90% confidence intervals for relative risk, odds ratio, and risk differences all contain 0, hence, there is no statistically significant sex difference in severe diabetes risk among diabetics at this confidence level.\n\nA drawback of this analysis is that the dataset disregards other underlying confounding factors that contribute to the development of severe diabetes, such as other underlying health issues, food access, healthcare access, etc. In addition, even though retinopathy is a common clinical characteristic of worsening diabetes, it is not the defining feature of severe diabetes. Therefore, we cannot rule out sex to be an intrinsic factor that contributes to the difference in the severity of diabetes between males and females.\n\n# Session Info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessioninfo::session_info()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n─ Session info ───────────────────────────────────────────────────────────────\n setting  value\n version  R version 4.6.1 (2026-06-24 ucrt)\n os       Windows 11 x64 (build 26200)\n system   x86_64, mingw32\n ui       RTerm\n language (EN)\n collate  English_United States.utf8\n ctype    English_United States.utf8\n tz       America/New_York\n date     2026-09-28\n pandoc   3.10 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)\n quarto   1.10.18 @ C:\\\\PROGRA~1\\\\RStudio\\\\resources\\\\app\\\\bin\\\\quarto\\\\bin\\\\quarto.exe\n\n─ Packages ───────────────────────────────────────────────────────────────────\n package           * version date (UTC) lib source\n backports           1.5.1   2026-04-03 [1] CRAN (R 4.6.1)\n broom             * 1.0.13  2026-05-14 [1] CRAN (R 4.6.1)\n cli                 3.6.6   2026-04-09 [1] CRAN (R 4.6.1)\n digest              0.6.39  2025-11-19 [1] CRAN (R 4.6.1)\n dplyr             * 1.2.1   2026-04-03 [1] CRAN (R 4.6.1)\n evaluate            1.0.5   2025-08-27 [1] CRAN (R 4.6.1)\n farver              2.1.2   2024-05-13 [1] CRAN (R 4.6.1)\n fastmap             1.2.0   2024-05-15 [1] CRAN (R 4.6.1)\n fontBitstreamVera   0.1.1   2017-02-01 [1] CRAN (R 4.6.1)\n fontLiberation      0.1.0   2016-10-15 [1] CRAN (R 4.6.1)\n fontquiver          0.2.1   2017-02-01 [1] CRAN (R 4.6.1)\n forcats           * 1.0.1   2025-09-25 [1] CRAN (R 4.6.1)\n foreign             0.8-91  2026-01-29 [2] CRAN (R 4.6.1)\n gdtools             0.5.1   2026-05-25 [1] CRAN (R 4.6.1)\n generics            0.1.4   2025-05-09 [1] CRAN (R 4.6.1)\n ggformula         * 1.0.1   2026-01-17 [1] CRAN (R 4.6.1)\n ggiraph             0.9.6   2026-02-21 [1] CRAN (R 4.6.1)\n ggplot2           * 4.0.3   2026-04-22 [1] CRAN (R 4.6.1)\n ggridges            0.5.7   2025-08-27 [1] CRAN (R 4.6.1)\n glue                1.8.1   2026-04-17 [1] CRAN (R 4.6.1)\n gtable              0.3.6   2024-10-25 [1] CRAN (R 4.6.1)\n haven               2.5.5   2025-05-30 [1] CRAN (R 4.6.1)\n hms                 1.1.4   2025-10-17 [1] CRAN (R 4.6.1)\n htmltools           0.5.9   2025-12-04 [1] CRAN (R 4.6.1)\n htmlwidgets         1.6.4   2023-12-06 [1] CRAN (R 4.6.1)\n httr                1.4.8   2026-02-13 [1] CRAN (R 4.6.1)\n jsonlite            2.0.0   2025-03-27 [1] CRAN (R 4.6.1)\n kableExtra        * 1.4.1   2026-07-08 [1] CRAN (R 4.6.1)\n knitr             * 1.51    2025-12-20 [1] CRAN (R 4.6.1)\n labeling            0.4.3   2023-08-29 [1] CRAN (R 4.6.1)\n labelled            2.16.1  2026-08-20 [1] CRAN (R 4.6.1)\n lattice           * 0.23-1  2026-08-12 [1] CRAN (R 4.6.1)\n lifecycle           1.0.5   2026-01-08 [1] CRAN (R 4.6.1)\n lubridate         * 1.9.5   2026-02-04 [1] CRAN (R 4.6.1)\n magrittr            2.0.5   2026-04-04 [1] CRAN (R 4.6.1)\n MASS                7.3-66  2026-07-15 [1] CRAN (R 4.6.1)\n Matrix            * 1.7-6   2026-07-25 [1] CRAN (R 4.6.1)\n mosaic              1.10.2  2026-05-13 [1] CRAN (R 4.6.1)\n mosaicCore          0.9.5   2025-07-30 [1] CRAN (R 4.6.1)\n mosaicData        * 0.20.4  2023-11-05 [1] CRAN (R 4.6.1)\n naniar            * 1.1.0   2024-03-05 [1] CRAN (R 4.6.1)\n nhanesA           * 1.4.1   2025-10-14 [1] CRAN (R 4.6.1)\n otel                0.2.0   2025-08-29 [1] CRAN (R 4.6.1)\n patchwork         * 1.3.2   2025-08-25 [1] CRAN (R 4.6.1)\n pillar              1.11.1  2025-09-17 [1] CRAN (R 4.6.1)\n pkgconfig           2.0.3   2019-09-22 [1] CRAN (R 4.6.1)\n plyr                1.8.9   2023-10-02 [1] CRAN (R 4.6.1)\n purrr             * 1.2.2   2026-04-10 [1] CRAN (R 4.6.1)\n R6                  2.6.1   2025-02-15 [1] CRAN (R 4.6.1)\n RColorBrewer        1.1-3   2022-04-03 [1] CRAN (R 4.6.1)\n Rcpp                1.1.2   2026-07-05 [1] CRAN (R 4.6.1)\n readr             * 2.2.0   2026-02-19 [1] CRAN (R 4.6.1)\n rlang               1.3.0   2026-07-05 [1] CRAN (R 4.6.1)\n rmarkdown           2.31    2026-03-26 [1] CRAN (R 4.6.1)\n rstudioapi          0.19.0  2026-06-11 [1] CRAN (R 4.6.1)\n rvest               1.0.5   2025-08-29 [1] CRAN (R 4.6.1)\n S7                  0.2.2   2026-04-22 [1] CRAN (R 4.6.1)\n scales              1.4.0   2025-04-24 [1] CRAN (R 4.6.1)\n sessioninfo         1.2.4   2026-06-04 [1] CRAN (R 4.6.1)\n stringi             1.8.9   2026-08-04 [1] CRAN (R 4.6.1)\n stringr           * 1.6.0   2025-11-04 [1] CRAN (R 4.6.1)\n svglite             2.2.2   2025-10-21 [1] CRAN (R 4.6.1)\n systemfonts         1.3.2   2026-03-05 [1] CRAN (R 4.6.1)\n textshaping         1.0.5   2026-03-06 [1] CRAN (R 4.6.1)\n tibble            * 3.3.1   2026-01-11 [1] CRAN (R 4.6.1)\n tidyr             * 1.3.2   2025-12-19 [1] CRAN (R 4.6.1)\n tidyselect          1.2.1   2024-03-11 [1] CRAN (R 4.6.1)\n tidyverse         * 2.0.0   2023-02-22 [1] CRAN (R 4.6.1)\n timechange          0.4.0   2026-01-29 [1] CRAN (R 4.6.1)\n tzdb                0.5.0   2025-03-15 [1] CRAN (R 4.6.1)\n utf8                1.2.6   2025-06-08 [1] CRAN (R 4.6.1)\n vctrs               0.7.3   2026-04-11 [1] CRAN (R 4.6.1)\n viridisLite         0.4.3   2026-02-04 [1] CRAN (R 4.6.1)\n visdat              0.6.0   2023-02-02 [1] CRAN (R 4.6.1)\n withr               3.0.3   2026-06-19 [1] CRAN (R 4.6.1)\n xfun                0.60    2026-07-09 [1] CRAN (R 4.6.1)\n xml2                1.6.0   2026-06-22 [1] CRAN (R 4.6.1)\n yaml                2.3.12  2025-12-10 [1] CRAN (R 4.6.1)\n\n [1] C:/Users/khoit/AppData/Local/R/win-library/4.6\n [2] C:/Program Files/R/R-4.6.1/library\n * ── Packages attached to the search path.\n\n──────────────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "study-1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}